#Santosh
FROM ubuntu:latest
USER root
RUN apt-get update -y
RUN apt update -y
RUN apt-get install ca-certificates -y
RUN apt install iptables -y
RUN apt install vim -y
RUN apt install lxc -y
RUN apt install podman -y
