#Santosh
FROM ubuntu:latest
USER root
RUN apt-get update
RUN apt update
RUN apt-get install ca-certificates -y
RUN apt install iptables -y
RUN apt install vim -y
RUN apt install lxc -y
RUN apt install docker.io -y
RUN docker --version